"if"                          IF;
"else"                        ELSE;
"int"                         INT;
"float"                       FLOAT;
"string"                      STRING;

"\+"                          PLUS;
"\-"                          MINUS;
"\*"                          MULTIPLY;
"/"                           DIVIDE;

"="                           ASSIGN;
"=="                          EQUALS;
"!="                          NOT_EQUALS;
">"                           GREATER_THAN;
"<"                           LESS_THAN;
">="                          GREATER_THAN_OR_EQUAL;
"<="                          LESS_THAN_OR_EQUAL;

"\{"                          LBRACE;
"\}"                          RBRACE;
"\["                          LBRACKET;
"\]"                          RBRACKET;
"\("                          LPAR;
"\)"                          RPAR;

"true"                        TRUE;
"false"                       FALSE;

"[a-zA-Z][a-zA-Z0-9]*"        IDENT;
"[0-9]*"                      NUMBER;

"\;"                           SEMI;
"[ \n\r\t]"                   ;